os: linux
services: docker
language: python
stages:
  - unittest
  - deploy

jobs:
  include:
    - stage: unittest
      script: python3 -m pytest -v
    - stage: deploy
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker build -f Dockerfile -t $DOCKER_REPO:latest .
        - docker push $DOCKER_REPO
  
